# Generated by Django 6.1.1 on 2026-09-12 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("population", models.IntegerField()),
                ("area_sq_km", models.IntegerField()),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=255)),
                ("mayor_name", models.CharField(max_length=255)),
                (
                    "date_of_last_mayoral_election",
                    models.DateField(blank=True, null=True),
                ),
                ("population", models.IntegerField()),
                ("elevation_metres", models.IntegerField(blank=True, null=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geography.country",
                    ),
                ),
            ],
        ),
    ]
