# Generated by Django 6.1.1 on 2026-09-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geography", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="City",
        ),
    ]
